# Generated by Django 6.0.3 on 2026-04-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workout',
            name='unique_workout_per_user_per_date',
        ),
    ]
